services:
  db:
    image: mysql
    container_name: 'dmg_mysql_cont'
    environment:
      - MYSQL_ROOT_PASSWORD=S@ilth3wave$
      - MYSQL_DATABASE=discount_my_groceries
    volumes:
      - /var/lib/mysql:/var/lib/mysql_cont
    restart: always
  dmg_gunicorn:
    volumes:
      - ./static:/static
    env_file:
      - .env
    build:
      context: .
    container_name: 'dmg_gunicorn_cont'
    ports:
      - 8001:8001
    depends_on:
      - db
  nginx:
    build: ./nginx
    container_name: 'dmg_nginx_cont'
    volumes:
      - ./static:/static
    ports:
      - 8080:8080
    depends_on:
      - dmg_gunicorn