version: '3.8'

services:
  dmg_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    container_name: 'dmg_gunicorn_cont'
    ports:
      -"8000:8000"
  nginx:
    build: ./nginx
    container_name: 'nginx_cont'
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - dmg_gunicorn

volumes:
  static: