services:
  db:
    image: mysql
    container_name: 'dmg_mysql_cont'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
    volumes:
      - /var/lib/mysql:/var/lib/mysql_cont
    ports:
      - 3360:3306
    
  dmg_gunicorn:
    volumes:
      - ./static:/static
    env_file:
      - .env
    build:
      context: .
    container_name: 'dmg_gunicorn_cont'
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: 'dmg_nginx_cont'
    volumes:
      - ./static:/static
    ports:
      - 81:81
    depends_on:
      - dmg_gunicorn
  