services:
  db:
    image: mysql
    container_name: 'dmg_mysql_cont'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PROTOCOL=${DB_PROTOCOL}
    volumes:
      - database:/var/lib/mysql_cont
    ports:
      - 3360:3306

  dmg_app:
    volumes:
      - static:/app/static/
    env_file:
      - .env
    build:
      context: .
    container_name: 'dmg_app_cont'
    ports:
      - 8001:8001
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./nginx
    container_name: 'dmg_nginx_cont'
    volumes:
      - static:/static/
    ports:
      - 81:81
    depends_on:
      - dmg_app

volumes:
  static:
  database:
