version: '3.8'

services:
  dmg_gunicorn:
    volumes:
      - ./static:/static
    env_file:
      - .env
    build:
      context: .
    container_name: 'dmg_gunicorn_cont'
    ports:
      -"8000:8000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    container_name: 'dmg_nginx_cont'
    volumes:
      - ./static:/static
    ports:
      - "8080:8080"
    depends_on:
      - dmg_gunicorn
  db:
    image: mysql
    container_name: 'dmg_mysql_cont'
    volumes:
      - /var/lib/mysql:var/lib/mysql_cont